---
- name: deploy gitlab vm
  hosts: localhost
  connection: local
  vars_files:
    vars/jsvault.yml
  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "https://{{ engine_fqdn }}/ovirt-engine/api"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
  tasks:
  - name: Create and run VM from template
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      ballooning_enabled: "{{ vm_ballooning_enabled }}"
      high_availability: "{{ vm_high_availability }}"
      memory_guaranteed: "{{vm_memory}}"
      state: running
      wait: yes
      cloud_init:
         host_name: "{{ vm_name }}"
    register: vm_created

  # Create and attach new disk to "{{ vm_name }}"
  - ovirt_disks:
      name: "{{ vm_name }}_data01"
      vm_name: "{{ vm_name }}"
      size: 10GiB "{{ vm_disk_size | default('100GiB') }}"
      format: cow
      interface: virtio
    when: vm_created.changed

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"