---
- name: deploy gitlab vm
  hosts: localhost
  connection: local
  #vars_files:
   # vars/jsvault.yml
  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "https://{{ engine_fqdn }}/ovirt-engine/api"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
  tasks:
  - name: Create and run VM from template
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ vm_template }}"
      cluster: "{{ engine_cluster }}"
      memory: "{{vm_memory}}"
      ballooning_enabled: "{{ vm_ballooning_enabled }}"
      high_availability: "{{ vm_high_availability }}"
      memory_guaranteed: "{{vm_memory}}"
      state: running
      wait: yes
      cloud_init:
        host_name: "{{ vm_name }}"
        dns_servers: '192.168.120.208'
        nic_boot_protocol: static
        nic_ip_address: 192.168.160.35
        nic_netmask: 255.255.240.0
        nic_gateway: 192.168.120.208
        nic_name: eth0
    register: vm_created

  # Create and attach new datadisk to "{{ vm_name }}"
  - ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name | replace('.', '_') }}_data01"
      vm_name: "{{ vm_name }}"
      description: "{{ vm_disk_description_data | default('Data disk') }}"
      size: "{{ vm_disk_size | default('100GiB') }}"
      storage_domain: "{{ vm_storage_domain }}"
      format: cow
      interface: virtio_scsi
      state: attached
    when: vm_created.changed

  # Create and attach new disk to "{{ vm_name }}"
  - ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name | replace('.','_')}}_backup01"
      vm_name: "{{ vm_name }}"
      description: "{{ vm_disk_description_backup | default('Backup Disk') }}"
      size: "{{ vm_disk_size | default('100GiB') }}"
      storage_domain: "{{ vm_storage_domain }}"
      format: cow
      interface: virtio_scsi
      state: attached
    when: vm_created.changed

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"