---
- name: format disks for data and backup
  hosts: gitlab_test
  gather_facts: false
  tasks:
  - name: Collect only facts about disks
    setup:
      gather_subset:
      - hardware

  - name: Output disks
    debug:
      var: hostvars[inventory_hostname].ansible_devices.keys() | list
